### ISSUE TITLE
compiling for ubuntu 64 bit

### ISSUE THREAD

**Issue by antran89** [jackculpepper/yael#1]
Hi @jackculpepper , 
I downloaded your code, but I cannot install it successfully on Ubuntu 64bits for Matlab interface. I met the below error.

yael4matlab.a(nn.o): In function `add_matmul':
/home/tranlaman/Desktop/workspace/yael-master/matlab/../yael/nn.c:102: undefined reference to`sgemm_'
yael4matlab.a(nn.o): In function `add_matvecmul':
/home/tranlaman/Desktop/workspace/yael-master/matlab/../yael/nn.c:119: undefined reference to`sgemv_'
yael4matlab.a(nn.o): In function `mat_product':
/home/tranlaman/Desktop/workspace/yael-master/matlab/../yael/nn.c:309: undefined reference to`sgemm_'
collect2: ld returned 1 exit status

```
mex: link of ' "yael_kmeans.mexa64"' failed.
```

I even downloaded a new version of yael, but also did not install successfully. Please try to help me figure out. Thanks

**Comment by antran89** [comment]
I solved the problem because the configurations of Matlab in `~/.matlab` is not correct by default for Ubuntu.

**Comment by jasica528** [comment]
Can u tell me how u solved it? I'm facing the same problem.

**Comment by antran89** [comment]
@jasica528 Hi, for long time, I do not remember correctly.
Some configuration with mex is wrong in Ubuntu. For example, in ~/.matlab/R2012a/mexopts.sh, I fixed as following. I do not know whether it is the case in your example. Just replac `LDFLAGS` as mine:

```
#----------------------------------------------------------------------------
            ;;
        glnxa64)
#----------------------------------------------------------------------------
            RPATH="-Wl,-rpath,$TMW_ROOT/bin/$Arch"
            # StorageVersion: 1.0
            # CkeyName: GNU C
            # CkeyManufacturer: GNU
            # CkeyLanguage: C
            # CkeyVersion:
            CC='gcc'
            CFLAGS='-ansi -D_GNU_SOURCE'
            CFLAGS="$CFLAGS  -fexceptions"
            CFLAGS="$CFLAGS -fPIC -fno-omit-frame-pointer -pthread"
            CLIBS="$RPATH $MLIBS -lm"
            COPTIMFLAGS='-O -DNDEBUG'
            CDEBUGFLAGS='-g'
            CLIBS="$CLIBS -lstdc++"
#
            # C++keyName: GNU C++
            # C++keyManufacturer: GNU
            # C++keyLanguage: C++
            # C++keyVersion: 
            CXX='g++'
            CXXFLAGS='-ansi -D_GNU_SOURCE'
            CXXFLAGS="$CXXFLAGS -fPIC -fno-omit-frame-pointer -pthread"
            CXXLIBS="$RPATH $MLIBS -lm"
            CXXOPTIMFLAGS='-O -DNDEBUG'
            CXXDEBUGFLAGS='-g'
#
            # FortrankeyName: gfortran
            # FortrankeyManufacturer: GNU
            # FortrankeyLanguage: Fortran
            # FortrankeyVersion: 
#
            FC='gfortran'
            FFLAGS='-fexceptions -fbackslash'
            FFLAGS="$FFLAGS -fPIC -fno-omit-frame-pointer"
            FLIBS="$RPATH $MLIBS -lm"
            FOPTIMFLAGS='-O'
            FDEBUGFLAGS='-g'
#
            LD="$COMPILER"
            LDEXTENSION='.mexa64'
#            LDFLAGS="-pthread -shared -Wl,--version-script,$TMW_ROOT/extern/lib/$Arch/$MAPFILE -Wl,--no-undefined"
        LDFLAGS="-pthread -shared -L$TMW_ROOT/bin/$Arch"
            LDOPTIMFLAGS='-O'
            LDDEBUGFLAGS='-g'
#
            POSTLINK_CMDS=':'
#----------------------------------------------------------------------------
```

**Comment by jasica528** [comment]
@antran89 it works! Thank u so much!
